export type Team = {
  id: string;
  name: string;
  short: string;
  city: string;
  division: string;
  conference: string;
  color: string;
  cardColor?: string;
  logo: string;
};
export type Game = {
  period?: number | null;
  periodType?: string | null;
  clock?: string | null;
  intermission?: boolean;
  homeShots?: number | null;
  awayShots?: number | null;
  id: number;
  season: number;
  type: number;
  date: string;
  start: string;
  state: string;
  scheduleState: string;
  venue: string;
  home: string;
  away: string;
  homeScore: number | null;
  awayScore: number | null;
  end: string;
  broadcasts: string[];
  round: number | null;
};
export type Snapshot = {
  season: number;
  updatedAt: string;
  source: string;
  games: Game[];
};
export type Player = {
  hits?: number | null;
  number?: number | null;
  headshot?: string;
  id: number;
  name: string;
  team: string;
  position: string;
  goals: number | null;
  assists: number | null;
  shots: number | null;
  plusMinus: number | null;
  pim: number | null;
  toi: string;
  saves: number | null;
  shotsAgainst: number | null;
  goalsAgainst: number | null;
};
export type Boxscore = {
  id: number;
  state: string;
  updatedAt: string;
  homeShots: number | null;
  awayShots: number | null;
  players: Player[];
};
export type PlayerSeason = {
  hits?: number | null;
  number?: number | null;
  id: number;
  name: string;
  team: string;
  position: string;
  gp: number;
  goals: number;
  assists: number;
  shots: number;
  plusMinus: number;
  pim: number;
  toi: number;
  headshot: string;
  savePct?: number | null;
  saves?: number | null;
  shotsAgainst?: number | null;
};
export type PlayerData = {
  season: number;
  gameType: number;
  updatedAt: string;
  skaters: PlayerSeason[];
  goalies: PlayerSeason[];
};
export type Scoreboard = { updatedAt: string; date: string; games: Game[] };
export type GameFeed = Game & {
  plays?: { id: number; order: number; period: number; periodType?: string; time: string; type: string; team: string | null; player: string | null; penalty: string | null; duration: number | null }[];
  situation?: { home: number | null; away: number | null; homePowerPlay: boolean; awayPowerPlay: boolean; seconds: number | null } | null;
  injuryStatus?: string;
  updatedAt: string;
  shots: {
    id: number;
    period: number;
    periodType: string;
    time: string;
    type: string;
    team: string;
    x: number | null;
    y: number | null;
  }[];
  goals: {
    id: number;
    period: number;
    time: string;
    team: string;
    player: string | null;
  }[];
  stats: { label: string; home: number; away: number }[];
};
export type EdgeData = {
  team: string;
  season: number;
  requestedSeason: number;
  updatedAt: string;
  gamesPlayed: number;
  metrics: {
    key: string;
    label: string;
    unit: string;
    value: number;
    average: number | null;
    rank: number | null;
  }[];
  zones: { label: string; value: number; average: number }[];
  locations: { label: string; shots: number; goals: number; average: number }[];
};
